 export const portfolioData = [
  {
    id: 1,
    title: "Earthlings I",
    subtitle: "Acrylic on wood",
    format: "A3 format",
    image: "/assets/img/Earthlings-I.jpg",
  },
  {
    id: 2,
    title: "Earthlings II",
    subtitle: "Acrylic on wood",
    format: "A3 format",
    image: "/assets/img/Earthlings-II.jpg",
  },
  {
    id: 3,
    title: "Earthlings III",
    subtitle: "Acrylic on wood",
    format: "A3 format",
    image: "/assets/img/Earthlings-III.jpg",
  },
  {
    id: 4,
    title: "Earthlings I-III Triptych",
    subtitle: "Acrylic on wood",
    format: "3 x A3 format",
    image: "/assets/img/Earthlings-I-III.jpg",
  },
  {
    id: 5,
    title: "Solo Exhibition at Elms Window Gallery, Leyton, London, UK",
    subtitle: "Selected works",
    format: "Various formats",
    videoId: "mR5TG3XNDYc",
  },
  {
    id: 6,
    title: "Reflection I-III",
    subtitle: "Acrylic on canvas",
    format: "3 x 8x6 inch canvas",
    image: "/assets/img/Reflection-I-III.jpg",
  },
  {
    id: 7,
    title: "Reflection I",
    subtitle: "Acrylic on canvas",
    format: "8x6 inch canvas",
    image: "/assets/img/Reflection-I.jpg",
  },
  {
    id: 8,
    title: "Reflection II",
    subtitle: "Acrylic on canvas",
    format: "8x6 inch canvas",
    image: "/assets/img/Reflection-II.jpg",
  },
  {
    id: 9,
    title: "Reflection III",
    subtitle: "Acrylic on canvas",
    format: "8x6 inch canvas",
    image: "/assets/img/Reflection-III.jpg",
  },
  {
    id: 10,
    title: "Grove Garden",
    subtitle: "Acrylic on wood",
    format: "97 x 61cm",
    image: "/assets/img/GroveGarden.jpg",
  },
  {
    id: 11,
    title: "Fruits of the forest",
    subtitle: "Acrylic on slate",
    format: "43 x 26cm",
    image: "/assets/img/Fruits-of-the-forest.jpg",
  },
  {
    id: 12,
    title: "Discovered Gardens I-III",
    subtitle: "Acrylic on wood",
    format: "24 x 10 inch for whole triptych",
    image: "/assets/img/Discovered-Gardens-I-III.jpg",
  },
  {
    id: 13,
    title: "Sunken",
    subtitle: "Acrylic on wood",
    format: "41 x 37.5cm",
    image: "/assets/img/Sunken.jpg",
  },
  {
    id: 14,
    title: "Storm in a sink",
    subtitle: "Oil on stainless steel",
    format: "54 x 57.5cm",
    image: "/assets/img/Storm-in-a-sink.jpg",
  },
  {
    id: 15,
    title: "Within",
    subtitle: "Acrylic on slate",
    format: "16 x 20 inch",
    image: "/assets/img/Within.jpg",
  },
  {
    id: 16,
    title: "Patterned Earth",
    subtitle: "Acrylic on wood",
    format: "16 x 20 inch",
    image: "/assets/img/metamorpho_earth-patterns.jpg",
  },
  {
    id: 17,
    title: "Heart of a Tree",
    subtitle: "Acrylic on wood",
    format: "61 x 167.5cm",
    image: "/assets/img/heart-of-a-tree.jpg",
  },
  {
    id: 26,
    title: "Corporeal",
    subtitle: "Acrylic on wood",
    format: "2 x 122 x 106.5cm",
    image: "/assets/img/Corporeal.jpg",
  },
  {
    id: 18,
    title: "Untitled",
    subtitle: "Acrylic on wood",
    format: "104.5 x 90.5cm",
    image: "/assets/img/Bird-icon.jpg",
  },
  {
    id: 19,
    title: "Limb-o",
    subtitle: "Acrylic on wood",
    format: "150 x 90.5cm",
    image: "/assets/img/Limb-o.jpg",
  },
  {
    id: 20,
    title: "Fishbone",
    subtitle: "Acrylic on slate",
    format: "25 x 15cm",
    image: "/assets/img/fishbone.jpg",
  },
  {
    id: 21,
    title: "KitKat",
    subtitle: "Acrylic on canvas",
    format: "5x7 inch",
    image: "/assets/img/KitKat.jpg",
  },
  {
    id: 22,
    title: "Chewy",
    subtitle: "Acrylic on canvas",
    format: "5x7 inch",
    image: "/assets/img/Chewy.jpg",
  },
  {
    id: 23,
    title: "Bluebird",
    subtitle: "Acrylic on slate",
    format: "45 x 25cm",
    image: "/assets/img/bluebird.jpg",
  },
  {
    id: 24,
    title: "Wholly animal",
    subtitle: "Acrylic on slate",
    format: "52 x 13.5cm",
    image: "/assets/img/whollyAnimal.jpg",
  },
  {
    id: 25,
    title: "Anemone",
    subtitle: "Acrylic on slate",
    format: "35 x 10cm",
    image: "/assets/img/anemone.jpg",
  },
  {
    id: 26,
    title: "Snailscape",
    subtitle: "Acrylic on slate",
    format: "50 x 10cm",
    image: "/assets/img/snailscape.jpg",
  },

];
