 export const portfolioData = [
  {
    id: 1,
    title: "Earthlings I",
    subtitle: "Acrylic on wood",
    format: "A3 format",
    image: "/assets/img/Earthlings-I.jpg",
  },
  {
    id: 2,
    title: "Earthlings II",
    subtitle: "Acrylic on wood",
    format: "A3 format",
    image: "/assets/img/Earthlings-II.jpg",
  },
  {
    id: 3,
    title: "Earthlings III",
    subtitle: "Acrylic on wood",
    format: "A3 format",
    image: "/assets/img/Earthlings-III.jpg",
  },
  {
    id: 4,
    title: "Earthlings I-III Triptych",
    subtitle: "Acrylic on wood",
    format: "3 x A3 format",
    image: "/assets/img/Earthlings-I-III.jpg",
  },
  {
    id: 5,
    title: "Solo Exhibition at Elms Window Gallery, Leyton, London, UK",
    subtitle: "Selected works",
    format: "Various formats",
    videoId: "mR5TG3XNDYc",
  },
  {
    id: 6,
    title: "Reflection I-III",
    subtitle: "Acrylic on canvas",
    format: "3 x 8x6 inch canvas",
    image: "/assets/img/Reflection-I-III.jpg",
  },
  {
    id: 7,
    title: "Reflection I",
    subtitle: "Acrylic on canvas",
    format: "8x6 inch canvas",
    image: "/assets/img/Reflection-I.jpg",
  },
  {
    id: 8,
    title: "Reflection II",
    subtitle: "Acrylic on canvas",
    format: "8x6 inch canvas",
    image: "/assets/img/Reflection-II.jpg",
  },
  {
    id: 9,
    title: "Reflection III",
    subtitle: "Acrylic on canvas",
    format: "8x6 inch canvas",
    image: "/assets/img/Reflection-III.jpg",
  },
  {
    id: 10,
    title: "KitKat",
    subtitle: "Acrylic on canvas",
    format: "5x7 inch",
    image: "/assets/img/KitKat.jpg",
  },
  {
    id: 11,
    title: "Chewy",
    subtitle: "Acrylic on canvas",
    format: "5x7 inch",
    image: "/assets/img/Chewy.jpg",
  },
  {
    id: 12,
    title: "Grove Garden",
    subtitle: "Acrylic on wood",
    format: "97 x 61cm",
    image: "/assets/img/GroveGarden.jpg",
  },
  {
    id: 13,
    title: "Sunken",
    subtitle: "Acrylic on wood",
    format: "41 x 37.5cm",
    image: "/assets/img/Sunken.jpg",
  },
  {
    id: 14,
    title: "Fruits of the forest",
    subtitle: "Acrylic on slate",
    format: "43 x 26cm",
    image: "/assets/img/Fruits-of-the-forest.jpg",
  },
];
