# File: .github/workflows/publish.yml
name: publish-to-github-pages
on:
  push:
    branches:
      - site

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
